### ISSUE TITLE
Consider a lit-html renderer for SkateJS

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/data-bound#13]
So, this project might need to be repurposed. I need to study DOM re-rendering more, because I'm not sure I understand why it needs to be re-rendered all of the time. Can't the properties just change, and then the DOM will repaint itself? Anyway, [lit-html](https://github.com/PolymerLabs/lit-html) looks like an interesting project. @treshugart mentioned that a lit-html renderer for SkateJS would be what I was looking for, so look into it. Writing that renderer might be the way to go. Though I still want vanilla WCs that call out to a simple function for data-binding with declarative event handling, I don't want to have to be called by a framework or library.

**Comment by treshugart** [comment]
Here's the renderer you're looking for along with example usage. All of this works with native imports, so you can just load it up in Canary with the flag on. Just make sure you `npm install skatejs lit-html` and write the HTML file to load the following JS and output the `<x-hello />` component.

```js
import { props, withProps } from './node_modules/skatejs/esnext/with-props.js';
import { withRender } from './node_modules/skatejs/esnext/with-render.js';
import { html } from './node_modules/lit-html/lib/lit-html.js';

class LitHtmlRenderer extends withRender(withProps()) {
  rendererCallback (renderRoot, renderCallback) {
    renderCallback().renderTo(renderRoot);
  }
}

class Hello extends LitHtmlRenderer {
  renderCallback ({ name }) {
    return html`<div>Hello, ${name}!</div>`;
  }
}

Hello.props = {
  name: { ...props.string, ...{ default: 'World' } }
};

customElements.define('x-hello', Hello);
```

To address some of your questions:

> I'm not sure I understand why it needs to be re-rendered all of the time.

I'm not exactly sure what you mean by "all of the time". Re-rendering / re-painting happens in response to properties changing, so I feel you already understand it maybe?

> Though I still want vanilla WCs that call out to a simple function for data-binding with declarative event handling, I don't want to have to be called by a framework or library.

Skate is essentially this because you're just extending mixins (or the default base `Component`). It feels like you want the "bare minimum". This is ideal, but I think in order to provide a predictable and well-defined / built custom element, there's a set of things that it should be providing as part of its core API. At the core of this would be proper attribute / property reflection and semantics. This is what `withProps` gives you. If you want rendering / data-binding, then `withRender` gives you the framework for defining that. The only opinionated aspect about Skate's rendering pipeline algorithm is that it will batch property updates and then call `rendererCallback()`. Inside that, it's up to the renderer to do whatever it needs to render. Whether this be a virtual DOM or a data-binding system, Skate doesn't care.

**Comment by lastmjs** [comment]
Thanks!

> I'm not sure I understand why it needs to be re-rendered all of the time.

In response to property changes, I don't quite understand why the entire DOM affected by that change needs to be re-rendered. I understand that effectively an `innerHTML` is being set with React/Virtual DOM and similar projects when properties change, correct? Why not just update the property and leave it at that? Let's say I have an input element as the only thing in my `body`:

```html
<body>
  <input id="theInput" type="text" value="hello">
</body>
```

Can't I just call `document.getElementById('theInput').value = 'good bye';` to update the element? The browser will detect the change and repaint. From what I've gathered, React/Virtual DOM and similar projects would do the following at the most basic level when the value property changed:

```html
document.body.innerHTML = `<input id="theInput" type="text" value="good bye">`;
```

I understand that re-rendering the whole DOM or parts of the DOM is more functional, but is it true that it is also more performant? Am I even thinking about this correctly?

**Comment by treshugart** [comment]
Virtual DOM implementations try and find the most efficient update possible. In this case, they will only update the `value` property just as you're doing manually. There is slightly more overhead in creating a virtual tree and diffing it, but it's unlikely that it will ever present itself as a problem. If it does, you likely have bigger problems than creating / diffing a large vdom tree.

**Comment by lastmjs** [comment]
It looks like `lit-html` is doing everything I wanted to do with data-bound and more. The algorithms we are using are very similar, but `lit-html`s are more advanced and efficient. It looks like an awesome project to use and potentially contribute to, so I'll probably stop work on this repo.
